title: "亚洲人本研究院 | PCIA"
baseurl: ""
url: "https://pcia.asia"
markdown: kramdown

permalink: /:categories/:title/

future: true

timezone: Asia/Shanghai

# 声明新的 collection：programs_zh & programs_en
collections:
  programs_zh:
    output: true
    permalink: /zh/programs/:title/
  programs_en:
    output: true
    permalink: /en/programs/:title/

# -- 1) 对 /zh 和 /en 文件夹下的页面做默认设置 --
defaults:
  # （A）静态页面：/zh 目录
  - scope:
      path: "zh"
      type: "pages"
    values:
      lang: zh
      categories: zh

  # （B）静态页面：/en 目录
  - scope:
      path: "en"
      type: "pages"
    values:
      lang: en
      categories: en

  # （C）博客文章：_posts/zh
  - scope:
      path: "_posts/zh"
      type: "posts"
    values:
      lang: zh
      categories: zh

  # （D）博客文章：_posts/en
  - scope:
      path: "_posts/en"
      type: "posts"
    values:
      lang: en
      categories: en

  # （E）项目（中文）：_programs/zh
  - scope:
      path: "_programs/zh"
      type: "programs_zh"
    values:
      lang: zh
      categories: zh

  # （F）项目（英文）：_programs/en
  - scope:
      path: "_programs/en"
      type: "programs_en"
    values:
      lang: en
      categories: en
