backend:
  name: git-gateway
  repo: yeeliu611/YeeLiu611
  branch: main
  proxy: false
  auth:
    client_id: Ov23lil8yXEgwjwxg75d
media_folder: "images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "pages"
    label: "页面"
    files:
      - file: "index.md"
        label: "首页"
        name: "homepage"
        fields:
          - { name: "title", label: "页面标题", widget: "string" }
          - { name: "hero_title", label: "首页大标题", widget: "string" }
          - { name: "hero_subtitle", label: "副标题", widget: "string" }
          - { name: "hero_btn", label: "按钮文字", widget: "string" }
          - { name: "intro_title", label: "介绍标题", widget: "string" }
          - { name: "intro_text", label: "介绍文本", widget: "text" }
          - { name: "body", label: "正文内容", widget: "markdown" }
      - file: "about.md"
        label: "关于我们"
        name: "about"
        fields:
          - { name: "title", label: "页面标题", widget: "string" }
          - { name: "body", label: "正文内容", widget: "markdown" }
      - file: "programs.md"
        label: "项目"
        name: "programs"
        fields:
          - { name: "title", label: "页面标题", widget: "string" }
          - { name: "body", label: "正文内容", widget: "markdown" }
      - file: "contact.md"
        label: "联系我们"
        name: "contact"
        fields:
          - { name: "title", label: "页面标题", widget: "string" }
          - { name: "body", label: "正文内容", widget: "markdown" }